import Head from 'next/head';

import Header from '../components/header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lype - Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Header />
      </main>
    </div>
  )
}
